# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenlight < Formula
  desc "TUI dashboard for GitHub Actions deployment approvals."
  homepage "https://github.com/wirya/greenlight"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.1/greenlight_darwin_amd64.tar.gz"
      sha256 "4645acd9b7dc72f8bb59cb80d9216df6cccaf8a9cf4d1ef5f4e217e461d5191d"

      define_method(:install) do
        bin.install "greenlight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.1/greenlight_darwin_arm64.tar.gz"
      sha256 "5da4a2c4218ca3554d952bee2ab26bd6725c54f3a24b56b90fda1b96b80b5e7a"

      define_method(:install) do
        bin.install "greenlight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.1/greenlight_linux_amd64.tar.gz"
      sha256 "1818e56dd641088d86c01e30901962c81e372139a33d3fc099821b0dfcec1459"
      define_method(:install) do
        bin.install "greenlight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.1/greenlight_linux_arm64.tar.gz"
      sha256 "ecb8d461a04a958651210a5fbb87fe50235ea7b11d9d66c92e11d456c4832939"
      define_method(:install) do
        bin.install "greenlight"
      end
    end
  end

  test do
    system "#{bin}/greenlight", "version"
  end
end
