# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenlight < Formula
  desc "TUI dashboard for GitHub Actions deployment approvals."
  homepage "https://github.com/wirya/greenlight"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.0/greenlight_darwin_amd64.tar.gz"
      sha256 "9c646e01f36e347350879f2a65f94b65050e7496906ed4be23968873740a0ce7"

      define_method(:install) do
        bin.install "greenlight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.0/greenlight_darwin_arm64.tar.gz"
      sha256 "dd87b2014f36b57f09508b74e4bd03b03b524123a5c529eeb73fe1e57e1544ce"

      define_method(:install) do
        bin.install "greenlight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.0/greenlight_linux_amd64.tar.gz"
      sha256 "a4670d64f8c73db9c93669b88c414afe33fe7c58024dfaedb4a62e1bd835c408"
      define_method(:install) do
        bin.install "greenlight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/greenlight/releases/download/v0.1.0/greenlight_linux_arm64.tar.gz"
      sha256 "81eee23b29673b3c065b10f1b46161683dce8f73179e2bbed06cd4ef21faa4be"
      define_method(:install) do
        bin.install "greenlight"
      end
    end
  end

  test do
    system "#{bin}/greenlight", "version"
  end
end
