# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reprac < Formula
  desc "Track unreleased changes across your repos — never forget to deploy again."
  homepage "https://github.com/adhaniscuber/reprac"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhaniscuber/reprac/releases/download/v0.1.1/reprac_darwin_amd64.tar.gz"
      sha256 "a1d46484d3e8dd1e0202c08ff35160d1cc5a390f695d0d0683b92c878852d41d"

      define_method(:install) do
        bin.install "reprac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhaniscuber/reprac/releases/download/v0.1.1/reprac_darwin_arm64.tar.gz"
      sha256 "fae0789b8ad622bf300deb85675636eb97dcb653f5f5ee0dd67d1e982ba1f746"

      define_method(:install) do
        bin.install "reprac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/reprac/releases/download/v0.1.1/reprac_linux_amd64.tar.gz"
      sha256 "239a1fb85f9a3893d83c554d5b52ad0a246f54eb3d0adf6e4aad37cc71286359"
      define_method(:install) do
        bin.install "reprac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adhaniscuber/reprac/releases/download/v0.1.1/reprac_linux_arm64.tar.gz"
      sha256 "4a6ac564a59882481a38aa99f9afc4a68326bc72c3a7813f9b26ada353700058"
      define_method(:install) do
        bin.install "reprac"
      end
    end
  end

  test do
    system "#{bin}/reprac", "version"
  end
end
